//! Automatic zsh shell-integration loading.
//!
//! Yutani's shell-aware features — the autocomplete popup (OSC 2122), prompt
//! marks / exit-status gutter (OSC 133), cwd reporting (OSC 7) — all depend on
//! the user's shell sourcing `shell-integration/yutani.zsh`. Making users add a
//! `source …` line to their `~/.zshrc` by hand is fragile (a stale path
//! silently disables everything) and a poor first-run experience.
//!
//! Instead we auto-load it the way kitty / Ghostty / VS Code do: since Yutani
//! forks the shell itself, we point the child's `$ZDOTDIR` at a Yutani-owned
//! directory whose wrapper dotfiles source the user's real startup files first,
//! then `yutani.zsh`. The integration script is **embedded in the binary**
//! (`include_str!`) and materialized to a runtime dir on launch, so there is no
//! external path that can go stale.
//!
//! Opt out by exporting `YUTANI_SHELL_INTEGRATION=0` (for users who wire the
//! integration up themselves). Only zsh is handled today; bash/fish are a
//! documented follow-up (see FEATURES.md).

use std::path::{Path, PathBuf};

/// The integration script, baked into the binary so it can't be missing or
/// out of date relative to the code that speaks its protocol.
const INTEGRATION_ZSH: &str = include_str!("../shell-integration/yutani.zsh");

/// Wrapper `.zshenv` for the Yutani ZDOTDIR. zsh reads this first; we source
/// the user's real `.zshenv` (from their original ZDOTDIR, captured in
/// `YUTANI_USER_ZDOTDIR`) without permanently moving `$ZDOTDIR`, so zsh still
/// reads our `.zprofile`/`.zshrc`/`.zlogin` for the later stages.
const WRAPPER_ZSHENV: &str = "\
# Auto-generated by Yutani — do not edit (regenerated each launch).
# Chain to the user's real zsh startup files, then load Yutani's integration.
if [[ -n \"${YUTANI_USER_ZDOTDIR-}\" && -f \"${YUTANI_USER_ZDOTDIR}/.zshenv\" ]]; then
  ZDOTDIR=\"$YUTANI_USER_ZDOTDIR\" source \"${YUTANI_USER_ZDOTDIR}/.zshenv\"
fi
";

const WRAPPER_ZPROFILE: &str = "\
# Auto-generated by Yutani — do not edit (regenerated each launch).
if [[ -n \"${YUTANI_USER_ZDOTDIR-}\" && -f \"${YUTANI_USER_ZDOTDIR}/.zprofile\" ]]; then
  ZDOTDIR=\"$YUTANI_USER_ZDOTDIR\" source \"${YUTANI_USER_ZDOTDIR}/.zprofile\"
fi
";

/// The `.zshrc` is where it matters: source the user's rc, then `yutani.zsh`
/// (after theirs so our zle hooks compose last), then restore `$ZDOTDIR` to the
/// user's value for the rest of the interactive session. `$YUTANI_ZDOTDIR` is
/// our own dir — used to locate `yutani.zsh` even if the user's rc reassigned
/// `$ZDOTDIR`.
const WRAPPER_ZSHRC: &str = "\
# Auto-generated by Yutani — do not edit (regenerated each launch).
if [[ -n \"${YUTANI_USER_ZDOTDIR-}\" && -f \"${YUTANI_USER_ZDOTDIR}/.zshrc\" ]]; then
  ZDOTDIR=\"$YUTANI_USER_ZDOTDIR\" source \"${YUTANI_USER_ZDOTDIR}/.zshrc\"
fi
# Restore ZDOTDIR for the rest of the session before anything reads it.
if [[ -n \"${YUTANI_USER_ZDOTDIR-}\" ]]; then
  export ZDOTDIR=\"$YUTANI_USER_ZDOTDIR\"
else
  unset ZDOTDIR
fi
# The system /etc/zshrc runs before this file (while our ZDOTDIR was still
# active) and on macOS sets HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history — pinning
# history into our dir. Rebase it back, but only if the user didn't point it
# somewhere of their own (in which case it won't be under our dir).
if [[ \"${HISTFILE-}\" == \"${YUTANI_ZDOTDIR}/\"* ]]; then
  HISTFILE=\"${YUTANI_USER_ZDOTDIR:-$HOME}/.zsh_history\"
fi
# Load Yutani's integration last, so its zle hooks compose on top and it reports
# the corrected HISTFILE (OSC 2124).
[[ -r \"${YUTANI_ZDOTDIR}/yutani.zsh\" ]] && source \"${YUTANI_ZDOTDIR}/yutani.zsh\"
";

const WRAPPER_ZLOGIN: &str = "\
# Auto-generated by Yutani — do not edit (regenerated each launch).
if [[ -n \"${YUTANI_USER_ZDOTDIR-}\" && -f \"${YUTANI_USER_ZDOTDIR}/.zlogin\" ]]; then
  ZDOTDIR=\"$YUTANI_USER_ZDOTDIR\" source \"${YUTANI_USER_ZDOTDIR}/.zlogin\"
fi
";

/// The (filename, contents) pairs written into the Yutani ZDOTDIR. The
/// integration script is last so a corrupt/partial write of it can't leave a
/// wrapper dangling. Pure (no I/O / env) so it's unit-testable.
fn zdotdir_files() -> [(&'static str, &'static str); 5] {
    [
        (".zshenv", WRAPPER_ZSHENV),
        (".zprofile", WRAPPER_ZPROFILE),
        (".zshrc", WRAPPER_ZSHRC),
        (".zlogin", WRAPPER_ZLOGIN),
        ("yutani.zsh", INTEGRATION_ZSH),
    ]
}

/// Whether `shell_path`'s program is zsh (the only shell we auto-integrate
/// today). Matched on the basename so `/bin/zsh`, `/opt/homebrew/bin/zsh`, and
/// a bare `zsh` all qualify.
pub fn is_zsh(shell_path: &str) -> bool {
    Path::new(shell_path)
        .file_name()
        .and_then(|n| n.to_str())
        == Some("zsh")
}

/// True when the user has opted out via `YUTANI_SHELL_INTEGRATION=0`.
fn opted_out() -> bool {
    std::env::var_os("YUTANI_SHELL_INTEGRATION")
        .map(|v| v == "0")
        .unwrap_or(false)
}

/// Directory the Yutani ZDOTDIR lives in: `<state_dir>/zdotdir`. Generated
/// runtime content, hence under the state dir rather than config.
fn zdotdir_path() -> Option<PathBuf> {
    Some(crate::state_dir()?.join("zdotdir"))
}

/// Materialize the Yutani ZDOTDIR and return its path, or `None` if integration
/// shouldn't be applied (opted out, non-zsh `$SHELL`, or any I/O failure — in
/// which case the shell simply launches without integration). Idempotent:
/// rewrites the files every call so the embedded script stays in sync with the
/// running binary. Cheap (five small files).
pub fn prepare_zdotdir() -> Option<PathBuf> {
    if opted_out() {
        return None;
    }
    let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/zsh".into());
    if !is_zsh(&shell) {
        return None;
    }
    let dir = zdotdir_path()?;
    std::fs::create_dir_all(&dir).ok()?;
    for (name, contents) in zdotdir_files() {
        // A failed write disables integration rather than launching a shell
        // with a half-written ZDOTDIR.
        std::fs::write(dir.join(name), contents).ok()?;
    }
    Some(dir)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_zsh_matches_basename_only() {
        assert!(is_zsh("/bin/zsh"));
        assert!(is_zsh("/opt/homebrew/bin/zsh"));
        assert!(is_zsh("zsh"));
        assert!(!is_zsh("/bin/bash"));
        assert!(!is_zsh("/usr/bin/fish"));
        assert!(!is_zsh("/bin/zsh-5.9")); // exact program name, not a prefix
        assert!(!is_zsh(""));
    }

    #[test]
    fn zshrc_wrapper_chains_user_rc_then_loads_integration() {
        let rc = zdotdir_files()
            .into_iter()
            .find(|(n, _)| *n == ".zshrc")
            .unwrap()
            .1;
        // Sources the user's real rc from their original ZDOTDIR ...
        assert!(rc.contains("source \"${YUTANI_USER_ZDOTDIR}/.zshrc\""));
        // ... then Yutani's integration ...
        assert!(rc.contains("source \"${YUTANI_ZDOTDIR}/yutani.zsh\""));
        // ... and the user-rc source precedes the integration source so our zle
        // hooks compose last.
        assert!(
            rc.find("/.zshrc\"").unwrap() < rc.find("/yutani.zsh\"").unwrap(),
            "user rc must be sourced before yutani.zsh"
        );
        // ... and restores ZDOTDIR afterward.
        assert!(rc.contains("export ZDOTDIR=\"$YUTANI_USER_ZDOTDIR\""));
        // ... and rebases HISTFILE if /etc/zshrc pinned it into our dir.
        assert!(rc.contains("HISTFILE=\"${YUTANI_USER_ZDOTDIR:-$HOME}/.zsh_history\""));
        // The HISTFILE fix must run before yutani.zsh so the OSC 2124 report is
        // correct.
        assert!(
            rc.find("HISTFILE=\"${YUTANI_USER_ZDOTDIR").unwrap()
                < rc.find("/yutani.zsh\"").unwrap(),
            "HISTFILE must be rebased before yutani.zsh is sourced"
        );
    }

    #[test]
    fn every_stage_wrapper_chains_its_user_file() {
        for (name, body) in zdotdir_files() {
            if name == "yutani.zsh" {
                continue;
            }
            assert!(
                body.contains(&format!("/{name}\"")),
                "{name} wrapper should source the user's {name}"
            );
        }
    }

    #[test]
    fn embedded_script_carries_the_osc_2122_hook() {
        // Guard against the integration script being emptied / losing the hook
        // that the autocomplete popup depends on.
        assert!(INTEGRATION_ZSH.contains("2122"));
        assert!(INTEGRATION_ZSH.contains("line-pre-redraw"));
    }
}
